{% set name = "jsonpath-python" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jsonpath-python-{{ version }}.tar.gz
  sha256: dd5be4a72d8a2995c3f583cf82bf3cd1a9544cfdabf2d22595b67aff07349666

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: True  # [py<36]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - test
  imports:
    - jsonpath
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v test

about:
  home: https://github.com/zhangxianbing/jsonpath-python
  summary: A more powerful JSONPath implementation in modern python
  description: |
    A more powerful JSONPath implementation in modern python.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://github.com/zhangxianbing/jsonpath-python
  dev_url: https://github.com/zhangxianbing/jsonpath-python

extra:
  recipe-maintainers:
    - jan-janssen
