{% set name = "jsonpath-python" %}
{% set version = "1.1.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: dded9932b4ec41fb8726e09c83afa4e6be618f938c2db287cc2a81723c639671

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - jsonpath
  commands:
    - pip check
    - pytest -v test
  requires:
    - pip
    - pytest >=8.0

about:
  home: https://github.com/zhangxianbing/jsonpath-python
  summary: A more powerful JSONPath implementation in modern python
  description: |
    A more powerful JSONPath implementation in modern python.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://github.com/zhangxianbing/jsonpath-python
  dev_url: https://github.com/zhangxianbing/jsonpath-python

extra:
  recipe-maintainers:
    - jan-janssen
